S---
title: "R Notebook"
output: html_notebook
---

Inegrantes del Equipo:

Antonio López Chávez - [A01741741]

Cristian Javier Cázares Mólina - [A01741952]

Melissa Paola Santana Meza - [A01740461] 

Luis Ángel Guzmán Iribe - [A01741757]

Set Up
```{r}
setwd(getwd())
library("seqinr")
library("ggplot2")
library("dplyr")

comp <- 0
virus <- 0
infoVirus <- function(fasta){
  virus <- fasta[[1]]
  seq <- virus[1:length(virus)]
  info <- summary(virus)
  cat("Tamaño de la secuencia:\n",info$length)
  cat("\n\nComposición de nucleótidos:")
  print(info$composition)
  
  cat("\nPorcentaje de Guanina-Citosina (GC):\n", info$GC*100,"%\n")
  
  cat("\nSecuencia original (muestra de 30):\n",seq[1:30])
  cat("\n\nSecuencia complementaria (muestra de 30):\n",complementaryStrand(seq)[1:30]) 
  
  compositions <- c(info$composition[1],info$composition[2],info$composition[3],info$composition[4]) 
  
  return(compositions)
}

virusComposition <- function(fasta){
  virus <- fasta[[1]]
  info <- summary(virus)
  
  compositions <- c(info$composition[1],info$composition[2],info$composition[3],info$composition[4]) 
  
  return(compositions)
}

complementaryStrand <- function(forwardDNA){
  compStrand <- c(1:length(forwardDNA))
  for(i in 1:length(forwardDNA)){
    if      (forwardDNA[i] == 'c'){compStrand[i] <- 'g'}
    else if (forwardDNA[i] == 'g'){compStrand[i] <- 'c'}
    else if (forwardDNA[i] == 'a'){compStrand[i] <- 't'}
    else if (forwardDNA[i] == 't'){compStrand[i] <- 'a'}
    else if (forwardDNA[i] == '-'){compStrand[i] <- '-'}
    else if (forwardDNA[i] == 'n'){compStrand[i] <- 'n'}
  }
  
  return(compStrand)
}
```

Zika Virus
```{r}
infoVirus(read.fasta("zika.fasta"))
zikaComposition <- virusComposition(read.fasta("zika.fasta"))
```

SARS Coronavirus
```{r}
infoVirus(read.fasta("SarsCovid.fasta"))
sarsComposition <- virusComposition(read.fasta("SarsCovid.fasta"))
```

Wuhan seafood market pneumonia virus isolate Wuhan-Hu-1
```{r}
infoVirus(read.fasta("Wu-Han-1.fasta"))
wuhan1Composition <- virusComposition(read.fasta("Wu-Han-1.fasta"))
```

Middle East respiratory syndrome coronavirus
```{r}
infoVirus(read.fasta("mers.fasta"))
mersComposition <- virusComposition(read.fasta("mers.fasta"))
```

Dengue virus 1
```{r}
infoVirus(read.fasta("Dengue.fasta"))
dengueComposition <- virusComposition(read.fasta("Dengue.fasta"))
```

H1N1
```{r}
infoVirus(read.fasta("H1N1.fasta"))
h1n1Composition <- virusComposition(read.fasta("H1N1.fasta"))
```

Graficación
```{r}
#Virus <- c("Zika","Sars","Wuhan 1","Mers","Dengue","H1N1")
Virus <- c(1,2,3,4,5,6)

Nucleotidos <- c(zikaComposition[1], sarsComposition[1], wuhan1Composition[1], mersComposition[1], dengueComposition[1], h1n1Composition[1]) #Este representa las adeninas, pero lo cambié a nucleotidos para corregir la grafica ES NECESARIO ARREGLARLO DESPUES

N_Citocinas <- c(zikaComposition[2], sarsComposition[2], wuhan1Composition[2], mersComposition[2], dengueComposition[2], h1n1Composition[2])

N_Guaninas <- c(zikaComposition[3], sarsComposition[3], wuhan1Composition[3], mersComposition[3], dengueComposition[3], h1n1Composition[3])

N_Timinas <- c(zikaComposition[4], sarsComposition[4], wuhan1Composition[4], mersComposition[4], dengueComposition[4], h1n1Composition[4])

dfCompositions <- data.frame(
  Virus,
  Nucleotidos,
  N_Citocinas,
  N_Guaninas,
  N_Timinas
)
```


```{r}

# En la grafica, los numeros representan los virus de la siguiente manera
#1 = Zika Virus
#2 = SARS Coronavirus 
#3 = Wuhan seafood market pneumonia virus isolate Wuhan-Hu-1
#4 = Middle East respiratory syndrome coronavirus
#5 = Dengue virus 1
#6 = H1N1 Virus

#Las lineas representan cada uno de los nucleotidos en su respectivo virus de la siguiente manera:
#Rojo = Adenina
#Azul = Citocina
#Verde = Guanina
#Negro = Timina

print(dfCompositions)
ggplot(dfCompositions, aes(Virus, Nucleotidos, group = 1)) + 
  geom_line(linetype="dashed", color = 'red', size = 1) +
  geom_line(linetype="dashed", y = N_Citocinas, color = 'blue', size = 1) +
  geom_line(linetype="dashed", y = N_Guaninas, color = 'green', size = 1) +
  geom_line(linetype="dashed", y = N_Timinas, color = 'black', size = 1)
```